name: Publish native binaries

on:
  workflow_dispatch:
  release:
    types: [created, edited]

jobs:
  buildOnWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup MS dev tools
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Setup MS VS tools
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew :yaml-config-updater-cli:nativeImage --no-daemon

      - name: Rename files
        shell: bash
        run: |
          mkdir upload
          cp yaml-config-updater-cli/build/graal/yaml-config-updater-cli.exe upload/yaml-updater.exe

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1.4.0
        continue-on-error: true
        with:
          version: latest
          files: upload/yaml-updater.exe
          args: "--lzma --best"

      - uses: actions/upload-artifact@v2
        with:
          name: yaml-updater.exe
          path: upload/yaml-updater.exe

  buildOnMac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew :yaml-config-updater-cli:nativeImage --no-daemon

      - name: Rename files
        run: |
          mkdir upload
          cp yaml-config-updater-cli/build/graal/yaml-config-updater-cli upload/yaml-updater-mac-amd64

      - name: Run UPX
        uses: svenstaro/upx-action@v2
        continue-on-error: true
        with:
          file: upload/yaml-updater-mac-amd64
          args: "--lzma --best"

      - uses: actions/upload-artifact@v2
        with:
          name: yaml-updater-mac-amd64
          path: upload/yaml-updater-mac-amd64

  buildOnLinux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew :yaml-config-updater-cli:shadowJar :yaml-config-updater-cli:nativeImage --no-daemon

      - name: Rename files
        run: |
          mkdir upload
          cp yaml-config-updater-cli/build/libs/*-all.jar upload/yaml-updater.jar
          cp yaml-config-updater-cli/build/graal/yaml-config-updater-cli upload/yaml-updater-linux-amd64

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1.4.0
        continue-on-error: true
        with:
          version: latest
          files: upload/yaml-updater-linux-amd64
          args: "--lzma --best"

      - uses: actions/upload-artifact@v2
        with:
          name: yaml-updater.jar
          path: upload/yaml-updater.jar

      - uses: actions/upload-artifact@v2
        with:
          name: yaml-updater-linux-amd64
          path: upload/yaml-updater-linux-amd64

  publishBuilds:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        artifact:
          - yaml-updater.exe
          - yaml-updater-mac-amd64
          - yaml-updater-linux-amd64
          - yaml-updater.jar
    needs: [buildOnWindows, buildOnMac, buildOnLinux]
    steps:
      - name: Download artifact ${{ matrix.artifact }}
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: upload

      - name: Upload ${{ matrix.artifact }}
        if: ${{ github.event_name == 'release' }}
        uses: JasonEtco/upload-to-release@master
        with:
          args: upload/${{ matrix.artifact }} application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
