name: Publish native binaries

on:
  pull_request:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build ${{ matrix.artifact }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - artifact: yaml-updater.exe
            os: windows-latest
            buildTask: nativeImage
            source: yaml-config-updater-cli/build/graal/yaml-config-updater-cli.exe
            experimental: true
          - artifact: yaml-updater-mac-amd64
            os: macos-latest
            source: yaml-config-updater-cli/build/graal/yaml-config-updater-cli
            buildTask: nativeImage
          - artifact: yaml-updater-linux-amd64
            os: ubuntu-latest
            source: yaml-config-updater-cli/build/graal/yaml-config-updater-cli
            buildTask: nativeImage
            experimental: true
          - artifact: yaml-updater.jar
            buildTask: shadowJar
            source: yaml-config-updater-cli/build/libs/*-all.jar
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental || false }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup MS dev tools
        if: ${{ endsWith(matrix.artifact, '.exe') }}
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Setup MS VS tools
        if: ${{ endsWith(matrix.artifact, '.exe') }}
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew :yaml-config-updater-cli:${{ matrix.buildTask }} --no-daemon

      - name: Rename files
        shell: bash
        run: |
          mkdir upload
          cp ${{ matrix.source }} "upload/${{ matrix.artifact }}"

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1.4.0
        if: ${{ ! contains(matrix.artifact, '.jar') }}
        continue-on-error: true
        with:
          version: latest
          files: upload/${{ matrix.artifact }}
          args: "--lzma --best"

      - name: Quick Test Binary
        if: ${{ ! contains(matrix.artifact, '.jar') }}
        run: ./upload/${{ matrix.artifact }} --version

      - name: Quick Test Jar
        if: ${{ contains(matrix.artifact, '.jar') }}
        run: java -jar upload/${{ matrix.artifact }} --version

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: upload/${{ matrix.artifact }}

  publishBuilds:
    runs-on: ubuntu-latest
    if: github.event.release.tag_name
    strategy:
      fail-fast: false
      matrix:
        artifact:
          - yaml-updater.exe
          - yaml-updater-mac-amd64
          - yaml-updater-linux-amd64
          - yaml-updater-alpine-amd64
          - yaml-updater.jar
    needs: [build]
    steps:
      - name: Download artifact ${{ matrix.artifact }}
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: upload

      - name: Upload ${{ matrix.artifact }}
        if: ${{ github.event_name == 'release' }}
        uses: JasonEtco/upload-to-release@master
        with:
          args: upload/${{ matrix.artifact }} application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
